# Generated by Django 5.0.4 on 2024-04-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='Введите название поля, которое будет в таблице', max_length=100, verbose_name='Название поля')),
            ],
        ),
    ]
